import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        series: resolve(__dirname, 'pages/series/series.html'),
        films: resolve(__dirname, 'pages/films/films.html'),
        blade_runner: resolve(__dirname, 'pages/films/details/accueil/blade_runner_2049.html'),
        django: resolve(__dirname, 'pages/films/details/accueil/django.html'),
        f1_the_movie: resolve(__dirname, 'pages/films/details/accueil/f1_the_movie.html'),
        fury: resolve(__dirname, 'pages/films/details/accueil/fury.html'),
        goodfellas: resolve(__dirname, 'pages/films/details/accueil/goodfellas.html'),
        interstellar: resolve(__dirname, 'pages/films/details/accueil/interstellar.html'),
        prisoners: resolve(__dirname, 'pages/films/details/accueil/prisoners.html'),
        the_dark_knight: resolve(__dirname, 'pages/films/details/accueil/the_dark_knight.html'),
        the_truman_show: resolve(__dirname, 'pages/films/details/accueil/the_truman_show.html'),
        bullet_train: resolve(__dirname, 'pages/films/details/action/bullet_train.html'),
        extraction2: resolve(__dirname, 'pages/films/details/action/extraction2.html'),
        john_wick2: resolve(__dirname, 'pages/films/details/action/john_wick2.html'),
        john_wick4: resolve(__dirname, 'pages/films/details/action/johnwick4.html'),
        madmax: resolve(__dirname, 'pages/films/details/action/madmax.html'),
        mission_impossible_dead_reckoning: resolve(__dirname, 'pages/films/details/action/mission_impossible_dead_reckoning.html'),
        mission_impossible: resolve(__dirname, 'pages/films/details/action/mission_impossible.html'),
        no_time_to_die: resolve(__dirname, 'pages/films/details/action/no_time_to_die.html'),
        road_house: resolve(__dirname, 'pages/films/details/action/road_house.html'),
        tenet: resolve(__dirname, 'pages/films/details/action/tenet.html'),
        the_beekeeper: resolve(__dirname, 'pages/films/details/action/the_beekeeper.html'),
        top_gun_maverick: resolve(__dirname, 'pages/films/details/action/top_gun_maverik.html'),
        avatar: resolve(__dirname, 'pages/films/details/blockbuster/avatar.html'),
        avengers_endgame: resolve(__dirname, 'pages/films/details/blockbuster/avengers_endgame.html'),
        avanger_infinity_war: resolve(__dirname, 'pages/films/details/blockbuster/avengers_infinity_war.html'),
        barbie: resolve(__dirname, 'pages/films/details/blockbuster/barbie.html'),
        dune_part2: resolve(__dirname, 'pages/films/details/blockbuster/dune_part2.html'),
        joker: resolve(__dirname, 'pages/films/details/blockbuster/joker.html'),
        jurrasic_world: resolve(__dirname, 'pages/films/details/blockbuster/jurassic_world.html'),
        oppenheimer: resolve(__dirname, 'pages/films/details/blockbuster/oppenheimer.html'),
        spieder_man_no_way_home : resolve(__dirname, 'pages/films/details/blockbuster/spider_man_no_way_home.html'),
        star_wars_the_force_awakens: resolve(__dirname, 'pages/films/details/blockbuster/star_wars_the_force_awakens.html'),
        the_batman: resolve(__dirname, 'pages/films/details/blockbuster/the_batman.html'),
        three_billboards: resolve(__dirname, 'pages/films/details/policier/3_billboards.html'),
        boston_strangle: resolve(__dirname, 'pages/films/details/policier/boston_strangler.html'),
        couteux_a_tirer: resolve(__dirname, 'pages/films/details/policier/couteaux_a_tires.html'),
        les_veuves: resolve(__dirname, 'pages/films/details/policier/les_veuves.html'),
        nice_guy: resolve(__dirname, 'pages/films/details/policier/nice_guy.html'),
        nightcrawler: resolve(__dirname, 'pages/films/details/policier/nightcrawler.html'),
        reptile: resolve(__dirname, 'pages/films/details/policier/reptile.html'),
        sicario: resolve(__dirname, 'pages/films/details/policier/sicario.html'),
        the_gentleman: resolve(__dirname, 'pages/films/details/policier/the_gentleman.html'),
        the_killer: resolve(__dirname, 'pages/films/details/policier/the_killer.html'),
        wind_river: resolve(__dirname, 'pages/films/details/policier/wind_river.html'),
        dune_part1: resolve(__dirname, 'pages/films/details/science_fiction/dune_part1.html'),
        hunger_games5: resolve(__dirname, 'pages/films/details/science_fiction/hunger_games5.html'),
        madmax_fury: resolve(__dirname, 'pages/films/details/science_fiction/madmax_fury_road.html'),
        matrix: resolve(__dirname, 'pages/films/details/science_fiction/matrix.htm'),
        ready_player_one: resolve(__dirname, 'pages/films/details/science_fiction/ready_player_one.html'),
        spiderman: resolve(__dirname, 'pages/films/details/science_fiction/spiderman.html'),
        the_creator: resolve(__dirname, 'pages/films/details/science_fiction/the_creator.html'),
        the_martian: resolve(__dirname, 'pages/films/details/science_fiction/the_martian.html'),
        breaking_bad: resolve(__dirname, 'pages/series/details/accueil/breaking_bad.html'),
        drive_to_survive: resolve(__dirname, 'pages/series/details/accueil/drive_to_survive.html'),
        get_gotti: resolve(__dirname, 'pages/series/details/accueil/get_gotti.html'),
        narcos: resolve(__dirname, 'pages/series/details/accueil/narcos.html'),
        the_wire: resolve(__dirname, 'pages/series/details/accueil/the_wire.html'),
        arnold: resolve(__dirname, 'pages/series/details/documentaire/arnold.html'),
        beckham: resolve(__dirname, 'pages/series/details/documentaire/beckham.html'),
        chernobyl: resolve(__dirname, 'pages/series/details/documentaire/chernobyl.html'),
        dont_fk_with_cats: resolve(__dirname, 'pages/series/details/documentaire/dont_fk_with_cats.html'),
        fear_city: resolve(__dirname, 'pages/series/details/documentaire/fear_city.html'),
        full_swing: resolve(__dirname, 'pages/series/details/documentaire/full_swing.html'),
        making_a_murderer: resolve(__dirname, 'pages/series/details/documentaire/making_a_murderer.html'),
        mcgregor_forever: resolve(__dirname, 'pages/series/details/documentaire/mcgregor_forever.html'),
        our_planet: resolve(__dirname, 'pages/series/details/documentaire/our_planet.html'),
        senna: resolve(__dirname, 'pages/series/details/documentaire/senna.html'),
        the_last_dance: resolve(__dirname, 'pages/series/details/documentaire/the_last_dance.html'),
        all_or_nothing: resolve(__dirname, 'pages/series/details/sport/all_or_nothing.html'),
        break_point: resolve(__dirname, 'pages/series/details/sport/break_point.html'),
        quaterback: resolve(__dirname, 'pages/series/details/sport/quaterback.html'),
        swagger: resolve(__dirname, 'pages/series/details/sport/swagger.html'),
        tour_de_france: resolve(__dirname, 'pages/series/details/sport/tour_de_france.html'),
        welcome_to_wrexham: resolve(__dirname, 'pages/series/details/sport/welcome_to_wrexham.html'),
        bodyguard: resolve(__dirname, 'pages/series/details/thriller/bodyguard.html'),
        dexter: resolve(__dirname, 'pages/series/details/thriller/dexter.html'),
        la_casa_de_papel: resolve(__dirname, 'pages/series/details/thriller/la_casa_de_papel.html'),
        lupin: resolve(__dirname, 'pages/series/details/thriller/lupin.html'),
        mindhunter: resolve(__dirname, 'pages/series/details/thriller/mindhunter.html'),
        mr_robot: resolve(__dirname, 'pages/series/details/thriller/mr_robot.html'),
        ozark: resolve(__dirname, 'pages/series/details/thriller/ozark.html'),
        ripley: resolve(__dirname, 'pages/series/details/thriller/ripley.html'),
        the_night_of: resolve(__dirname, 'pages/series/details/thriller/the_night_of.html'),
        the_sinner: resolve(__dirname, 'pages/series/details/thriller/the_sinner.html'),
        better_call_saul: resolve(__dirname, 'pages/series/details/us/better_call_saul.html'),
        euphoria: resolve(__dirname, 'pages/series/details/us/euphoria.html'),
        game_of_thrones: resolve(__dirname, 'pages/series/details/us/game_of_thrones.html'),
        house_of_cards: resolve(__dirname, 'pages/series/details/us/house_of_cards.html'),
        sopranos: resolve(__dirname, 'pages/series/details/us/sopranos.html'),
        stranger_things: resolve(__dirname, 'pages/series/details/us/stranger_things.html'),
        succession: resolve(__dirname, 'pages/series/details/us/succession.html'),
        the_boys: resolve(__dirname, 'pages/series/details/us/the_boys.html'),
        the_last_of_us: resolve(__dirname, 'pages/series/details/us/the_last_of_us.html'),
        the_mandalorian: resolve(__dirname, 'pages/series/details/us/the_mandalorian.html'),
        the_walking_dead: resolve(__dirname, 'pages/series/details/us/the_walking_dead.html'),
        true_detective: resolve(__dirname, 'pages/series/details/us/true_detective.html'),
      },
    },
  },
});